CREATE DATABASE IF NOT EXISTS CUSTOMADMIN;
USE CUSTOMADMIN;
CREATE TABLE CREATEACCOUNT(
    Id INT NOT NULL AUTO_INCREMENT,
    f_name VARCHAR(64) NOT NULL,
    l_name VARCHAR(64) NOT NULL,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL, 
    password VARCHAR(64) NOT NULL,
     PRIMARY KEY(Id)
);

ALTER TABLE CREATEACCOUNT AUTO_INCREMENT=100;

CREATE TABLE LOGIN(
    Id INT NOT NULL ,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(64) NOT NULL,
     PRIMARY KEY(Id)
);

CREATE TABLE ADMINLOGIN(
    Id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(64) NOT NULL, PRIMARY KEY(Id)

);

ALTER TABLE ADMINLOGIN AUTO_INCREMENT=200;
