GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON CUSTOMADMIN.* TO 'admin'@'localhost' IDENTIFIED BY 'mamab';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON INVENTORY.* TO 'admin'@'localhost' IDENTIFIED BY 'mamab';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON SUBSCRIBER.* TO 'admin'@'localhost' IDENTIFIED BY 'mamab';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON CUSCOMPLAINTS.* TO 'admin'@'localhost' IDENTIFIED BY 'mamab';