CREATE DATABASE IF NOT EXISTS INVENTORY;
USE INVENTORY;

CREATE TABLE ITEMS(
    Id INT NOT NULL AUTO_INCREMENT,
    name_item VARCHAR(64) NOT NULL,
    selling_price INT(255) NOT NULL,
    cost_price INT(255) NOT NULL,
    quantity_instock INT(255) NOT NULL, 
    supplier VARCHAR(64) NOT NULL,
    quantity_sold INT(255) NOT NULL,
    perishable INT(64) NOT NULL,
     PRIMARY KEY(Id)
);

ALTER TABLE ITEMS AUTO_INCREMENT=10;

CREATE TABLE ORDERTABLE(
    Id INT NOT NULL AUTO_INCREMENT,
    f_name VARCHAR(64) NOT NULL,
    l_name VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL, 
    name_item VARCHAR(64) NOT NULL,
    selling_price INT(255) NOT NULL,
    quantity INT(62) NOT NULL,
    total INT(255) NOT NULL,
    dateadded DATETIME NOT NULL DEFAULT (NOW()),
    PRIMARY KEY(Id)
);

ALTER TABLE ORDERTABLE AUTO_INCREMENT=15;

