CREATE DATABASE IF NOT EXISTS SUBSCRIBER;
USE SUBSCRIBER;
CREATE TABLE SUBSCRIBERS(
    Id INT NOT NULL AUTO_INCREMENT,
   f_name VARCHAR(64) NOT NULL,
   l_name VARCHAR(64) NOT NULL,
   email VARCHAR(64) NOT NULL,
   dateadded DATETIME NOT NULL DEFAULT (NOW()),
   PRIMARY KEY(Id)
);

ALTER TABLE SUBSCRIBERS AUTO_INCREMENT=1000;
